theme: jekyll-theme-hacker
title: The Onyx Bash Project
show_downloads: true
description: The Onyx Bash Project is a set of tools/programs that run in the Linux terminal environment and are completly text-based. The Onyx Bash Project is using the GNU GPL and is Free Software!
gems:
      - jekyll-sitemap
